version: '2'
services:

  #############################
  # Exciting micro services
  #############################
  edge-service:
    container_name: edge-service
    image: peavers/edge-service
    restart: always
    external_links:
      - config-service:config-service
      - eureka-service:eureka-service
    ports:
      - 80:8080
    environment:
    - TZ=Pacific/Auckland
    - SPRING_PROFILES_ACTIVE=docker
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  instance-service:
    container_name: instance-service
    image: peavers/instance-service
    restart: always
    external_links:
      - config-service:config-service
      - eureka-service:eureka-service
    environment:
    - TZ=Pacific/Auckland
    - SPRING_PROFILES_ACTIVE=docker
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  restore-service:
    container_name: restore-service
    image: peavers/restore-service
    restart: always
    external_links:
      - config-service:config-service
      - eureka-service:eureka-service
    environment:
    - TZ=Pacific/Auckland
    - SPRING_PROFILES_ACTIVE=docker
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-service:
    container_name: notification-service
    image: peavers/notification-service
    restart: always
    external_links:
      - config-service:config-service
      - eureka-service:eureka-service
    environment:
    - TZ=Pacific/Auckland
    - SPRING_PROFILES_ACTIVE=docker
    logging:
      options:
        max-size: "10m"
        max-file: "10"



  #############################
  # Boring management services
  #############################
  config-service:
    container_name: config-service
    image: peavers/config-service
    ports:
      - 8888:8888
    environment:
    - TZ=Pacific/Auckland
    - SPRING_CLOUD_CONFIG_SERVER_GIT_URI
    - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME
    - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD

  eureka-service:
    container_name: eureka-service
    image: peavers/eureka-service
    ports:
      - 8761:8761
    environment:
    - TZ=Pacific/Auckland