spring:
  application:
    name: node-service

# Since swordfish-commons brings in security, disable it here for the moment...
security:
  basic:
    enabled: false
management:
  security:
    enabled: false