version: '3.4'

services:
  edge-service:
    container_name: edge-service
    image: peavers/edge-service
    restart: always
    volumes:
      - /home/ec2-user/letsencrypt/keys/letsencrypt:/etc/letsencrypt/live/
    ports:
      - 443:8443
      - 8443:8443
    environment:
    - TZ=Pacific/Auckland
    - SPRING_PROFILES_ACTIVE=docker
    - SPRING_CLOUD_CONSUL_HOST=$CONSUL_HTTP_ADDR
    logging:
      options:
        max-size: "10m"
        max-file: "10"